### ISSUE TITLE
Expose a method like 'redisCommandArgv' in hiredis

### ISSUE THREAD

**Issue by yinqiwen** [0xsky/xredis#1]
Expose a common method 'execute_command' like 'redisCommandArgv' in hiredis, then xredis could be used even there is new redis command that xredis don't know.

**Comment by 0xsky** [comment]
you can use this funcations ：
    bool command_bool(const RedisDBIdx& dbi,                       const char* cmd, ...);
    bool command_status(const RedisDBIdx& dbi,                     const char* cmd, ...);
    bool command_integer(const RedisDBIdx& dbi, int64_t &intval,   const char* cmd, ...);
    bool command_string(const RedisDBIdx& dbi,  string &data,      const char* cmd, ...);
    bool command_list(const RedisDBIdx& dbi,    VALUES &vValue,    const char* cmd, ...);
    bool command_array(const RedisDBIdx& dbi,   ArrayReply& array, const char* cmd, ...);
