### ISSUE TITLE
get connection error with example & demo

### ISSUE THREAD

**Issue by AO-StreetArt** [0xsky/xredis#10]
Compiling the example and demo programs works, but running the examples results in a 'get connection error'

compile:

g++ -o ex -lpthread -lxredis demo.cpp `pkg-config --cflags --libs hiredis` -std=c++11

This is reproducible with Redis 3.2.0 on both Debian 8 and Ubuntu 14.04 LTS

**Comment by AO-StreetArt** [comment]
Be sure to update the file to the correct port for a redis instance.  I suggest changing the default value in the examples to 6379, which is the default port for an instance of Redis.

**Comment by 0xsky** [comment]
ok ,think you .

2016-06-14 12:37 GMT+08:00 Alex Barry <notifications@github.com>:
