### ISSUE TITLE
RedisConn::RedisReConnect()

### ISSUE THREAD

**Issue by nishinage** [0xsky/xredis#12]
最近使用xredis发现一个问题，如果redis设置了密码，与redis服务器断开连接后调用Keepalive重新连接 RedisConn::RedisReConnect()总是会失败，
看了下代码，问题出在mCtx切换逻辑有问题，修改为以下代码就可以重连了:
  if (NULL == mCtx) {
        return false;
    }

    bool bRet = false;
    redisContext *tmp_ctx = ConnectWithTimeout();
    if (NULL == tmp_ctx) {
        bRet = false;
    } else {
        redisFree(mCtx);
        mCtx = tmp_ctx;
        bRet = auth();
        if (bRet) {
            //redisFree(mCtx);
            //mCtx = tmp_ctx;
        }
    }

    mConnStatus = bRet;
    return bRet;

**Comment by 0xsky** [comment]
嗯，谢谢了，我合并下代码。
