### ISSUE TITLE
the function 'setex' checks reply type error

### ISSUE THREAD

**Issue by DyncKevin** [0xsky/xredis#15]
commit id: a61beb08c6114ec850d75446e8be4b516ed59ad7
description: the function '**setex**' in **xRedisClient_strings.cpp** checks wrong reply type

when invoke function '**setex**', if it is ok, this function actually returns reply which _reply->type_ is "_REDIS_REPLY_STATUS_" and _reply->str_ is "_OK_".
in current implement, '**setex**' checks _reply->ingeter_ which is always 0.

**Comment by 0xsky** [comment]
yes,you are right, bugs here , i will fix it . thx
