### ISSUE TITLE
namespace conflict

### ISSUE THREAD

**Issue by showmsg** [0xsky/xredis#20]
**How to resolve?**

```
/usr/local/include/xredis/xRedisClient.h:189:137: error: macro "setbit" passed 5 arguments, but takes just 2
     /* SETBIT      */  bool setbit(const RedisDBIdx& dbi,  const std::string& key,  int offset, int64_t newbitValue, int64_t oldbitValue);

```

**Comment by haitongz** [comment]
/usr/include/sys/param.h
have defined the setbit macro
solution
1: comments the setbit function in xredis if you do not use it
2: change the setbit function name in xredis and recompile it

**Comment by 0xsky** [comment]
好吧，我感觉还是很有必要加上namespace了。
已经加上了。

**Comment by 0xsky** [comment]
已经加上namespace了
