### ISSUE TITLE
Possible bug in xRedisClient::GetReply() 

### ISSUE THREAD

**Issue by gnyx** [0xsky/xredis#23]
Hi,
tested the pub/sub parts of your lib and found possible a memory leak in xRedisClient::GetReply().

the reply object is not freed when GetReply() returns. 
I made a threaded pub/sub application with 200 pub threads and it crashed quite quickly on a low-memory linux system.

When I add the following code snippet it works for hours:

```
diff --git a/libs/xredis/src/xRedisClient.cpp b/libs/xredis/src/xRedisClient.cpp
index 3e9cfd3..1dec330 100644
--- a/libs/xredis/src/xRedisClient.cpp
+++ b/libs/xredis/src/xRedisClient.cpp
@@ -403,7 +403,7 @@ int xRedisClient::GetReply(xRedisContext* ctx, ReplyData& vData)
             vData.push_back(item);
         }
     }
-
+   RedisPool::FreeReply(reply);
     return ret;
 }

``` 

Used the pub/sub implementation from your test implementation.
br

**Comment by 0xsky** [comment]
是的，这个地方没有释放，是有BUG的。
谢谢了。

**Comment by 0xsky** [comment]
bug fixed
