### ISSUE TITLE
Is there an agenda to implement transaction related commands?

### ISSUE THREAD

**Issue by ciasom** [0xsky/xredis#27]
The following five commands: 
    /* DISCARD  */
    /* EXEC     */
    /* MULTI    */
    /* UNWATCH  */
    /* WATCH    */

**Comment by 0xsky** [comment]
In my design, these commands are not much needed. Mainly because data is multi node and sub slice storage.
If you need him, I can implement these commands, and note that you can only use them in a single physical node scenario.

**Comment by ciasom** [comment]
Thanks. If they can be only used  in a single node, then don't bother to do that.
