### ISSUE TITLE
CentOS 6下无法正常make Install

### ISSUE THREAD

**Issue by soyoo** [0xsky/xredis#3]
mkdir -p /usr/local/include/xredis /usr/local/lib
cp -a xRedisClient.h /usr/local/include/xredis
cp: cannot stat `xRedisClient.h': No such file or directory
make: *** [install] Error 1

**Comment by 0xsky** [comment]
我这里测试没发现有这个问题呢，你能查下报错的原因么？

**Comment by soyoo** [comment]
@0xsky 我这段时间没有能运行CentOS 6虚拟机的电脑，没法查找原因。
