### ISSUE TITLE
使用xRedisClusterClient连续操作redis会失败

### ISSUE THREAD

**Issue by luis12** [0xsky/xredis#37]
使用 xRedisClusterClient 连续执行  SETEX、LPUSH这两个操作的时候，会出现操作全部失败的情况。比如，调用是这样子

for (int i=0;i<1000;i++){
      xRedisClusterClient::RedisCommand("SETEX ....");
      xRedisClusterClient::RedisCommand("LPUSH ....");
}

非常困惑。

**Comment by 0xsky** [comment]
使用   xRedisClusterClient 访问redis官方集群时，需要注意RedisCommand方法的参数问题，
xRedisClusterClient  redisClusterClient;
RedisResult result;   
redisClusterClient.RedisCommand(result, "hset %s %s %s ", **"key",** "hkey", "hval");

RedisCommand 的第三个参数一定要是 redis的key.

**Comment by 0xsky** [comment]
应该是之前的BUG，现在已经修复
