### ISSUE TITLE
Error Building Examples

### ISSUE THREAD

**Issue by AO-StreetArt** [0xsky/xredis#4]
Hello,
  I get the following error building the example files (demo.cpp and xredis-example.cpp) on Debian 8:

alex@Odysseus:~/Documents/Documents/cpp/xredis/xredis/examples$ g++ -lxredis -I /usr/local/include/xredis -o example xredis-example.cpp 
xredis-example.cpp:28:11: error: expected initializer before ‘RedisList1’
 RedisNode RedisList1[3]=

**Comment by mijiajia** [comment]
Yes, you should add semicolon after enum.

**Comment by cuiyy2019** [comment]
@mijiajia hello,
I also get the errors below building the xredis-test.cpp on win7 32bit:
xredis-test.cpp(37): error C2065: “__PRETTY_FUNCTION__”: 未声明的标识符
xredis-test.cpp(164): error C3861: “time”: 找不到标识符
I only include the "src" files without any libs or dlls.
Thanks!

**Comment by AO-StreetArt** [comment]
Fixed a few other problems with the demo.cpp, will submit a pull request.

Now seeing the below error, am I missing a dependency?

'alex@Odysseus:~/Documents/Documents/cpp/xredis/xredis/examples$ g++ -lxredis -I /usr/local/include/xredis -o demo demo.cpp 
//usr/local/lib/libxredis.so: undefined reference to `redisCommandArgv'
//usr/local/lib/libxredis.so: undefined reference to `pthread_mutexattr_settype'
//usr/local/lib/libxredis.so: undefined reference to `freeReplyObject'
//usr/local/lib/libxredis.so: undefined reference to `redisConnectWithTimeout'
//usr/local/lib/libxredis.so: undefined reference to `redisFree'
//usr/local/lib/libxredis.so: undefined reference to `pthread_mutexattr_init'
//usr/local/lib/libxredis.so: undefined reference to `redisvCommand'
//usr/local/lib/libxredis.so: undefined reference to `redisCommand'
collect2: error: ld returned 1 exit status'

**Comment by 0xsky** [comment]
fixed
