### ISSUE TITLE
ZUNIONSTORE这个操作怎么实现呢，目前没有提供接口

### ISSUE THREAD

**Issue by linminglei** [0xsky/xredis#42]

**Comment by linminglei** [comment]
sky能不能提示一下没有做的原因；
是不是可以自己去实现这个接口？

**Comment by 0xsky** [comment]
如果在没有数据分片的场景下，这个命令的实现是很容易的，参照其它命令的实现接口。
但是，在有多个节点使用数据分片的场景下，多个KEY数据是可能存储在不同的节点上的，
这个命令的实现要涉及到不同节点间的数据移动，有点麻烦。
所以暂时没有实现。

**Comment by linminglei** [comment]
感谢解答
