### ISSUE TITLE
 支持动态添加Redis服务节点？

### ISSUE THREAD

**Issue by XiaoYi-** [0xsky/xredis#45]
请问支持动态添加Redis服务节点吗，比如添加一个新的从节点后，客户端自动获取到新添加的节点IP：port然后建立连接。

**Comment by 0xsky** [comment]
不支持动态添加节点的

**Comment by 0xsky** [comment]
如果采用自定义数据分片存储方式，添加节点后，集群结构可能改变，可能会有key迁移。
如果使用官方集群，当前xRedisClusterClient不会主动检查集群节点变化，还是需要使用端重起程序，重新建立到集群的连接池。

**Comment by dwxiayi** [comment]
> 如果采用自定义数据分片存储方式，添加节点后，集群结构可能改变，可能会有key迁移。
> 如果使用官方集群，当前xRedisClusterClient不会主动检查集群节点变化，还是需要使用端重起程序，重新建立到集群的连接池。

有计划处理ask、move嘛？

**Comment by 0xsky** [comment]
已经在计划中，欢迎关注 
近期会把实现提交上来
