### ISSUE TITLE
smove bug

### ISSUE THREAD

**Issue by philipyao** [0xsky/xredis#47]
bool xRedisClient::smove(const RedisDBIdx& dbi,  const KEY& srckey, const KEY& deskey,  const VALUE& member){
    if (0==srckey.length()) {
        return false;
    }
    SETDEFAULTIOTYPE(MASTER);
    **return command_bool(dbi, "SMOVE %s", srckey.c_str(), deskey.c_str(), member.c_str());**
}

SMOVE这里少了2个 %s

**Comment by 0xsky** [comment]
你修改下，提交个fix上来？

**Comment by 0xsky** [comment]
have fixed
