### ISSUE TITLE
ZPOPMIN

### ISSUE THREAD

**Issue by livneros** [0xsky/xredis#53]
Hey,
Is there an option to set the ZPOPMIN command for sorted sets?
The Redis-CLI command is [ZPOPMIN](https://redis.io/commands/zpopmin)
Thanks!

**Comment by 0xsky** [comment]
已经看这到这两个新命令了，zpopmax/zpopmin, 我会尽快添加他们的实现。

**Comment by 0xsky** [comment]
命令已经添加。
