### ISSUE TITLE
测试examples下面的例子时连接失败

### ISSUE THREAD

**Issue by ts0923** [0xsky/xredis#55]
测试examples目录下的xRedisClusterClient_test.cpp和demo_cluster.cpp失败，xRedisClusterClient_test.cpp的错误信息为：Connection error:
demo_cluster.cpp的错误信息为：
error [get connection error] 
error [get connection error]

我的redis集群为：
[root@bogon redis-5.0.7]# ./src/redis-cli -p 7000 -c
127.0.0.1:7000> cluster nodes
7b4bf4a5649bfeff1e8f00ed19d60427a3186e44 127.0.0.1:7001@17001 master - 0 1587537818000 2 connected 5461-10922
108c9dd6bb50e93d4da1fa18a5035c8e82de0f14 127.0.0.1:7003@17003 slave 7b4bf4a5649bfeff1e8f00ed19d60427a3186e44 0 1587537818000 4 connected
2e8e631f85dd0b53e641d61921758d957c5a4cfb 127.0.0.1:7000@17000 myself,master - 0 1587537819000 1 connected 0-5460
44cab99b05667f2ebe732d93b9099156735ee699 127.0.0.1:7002@17002 master - 0 1587537819450 3 connected 10923-16383
ce8096bfdd13fe80e08aa24fcb00dec1a13cc383 127.0.0.1:7005@17005 slave 2e8e631f85dd0b53e641d61921758d957c5a4cfb 0 1587537820462 6 connected
6e06f99dc06bd8b8dce558ec5e10dca70a442d18 127.0.0.1:7004@17004 slave 44cab99b05667f2ebe732d93b9099156735ee699 0 1587537816381 5 connected

xRedisClusterClient_test.cpp运行时传入的参数是127.0.0.1 7000

demo_cluster.cpp中的集群配置如下：
/* 配置一个redis分片存储集群：共三个存储主节点 */
RedisNode RedisList1[3]=
{
    {0,"127.0.0.1", 7000, "", 2, 5, 0},
    {1,"127.0.0.1", 7001, "", 2, 5, 0},
    {2,"127.0.0.1", 7002, "", 2, 5, 0}
};

请问连接错误的原因是？

**Comment by ts0923** [comment]
补充下cluster info信息
127.0.0.1:7000> cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:6
cluster_my_epoch:1
cluster_stats_messages_ping_sent:18072
cluster_stats_messages_pong_sent:18226
cluster_stats_messages_sent:36298
cluster_stats_messages_ping_received:18221
cluster_stats_messages_pong_received:18072
cluster_stats_messages_meet_received:5
cluster_stats_messages_received:36298

**Comment by wanghonglu** [comment]
我也遇到了,解决了,因为作者的库src下有个hiredis的头文件,如果你自己下载的hiredis的版本跟这个头文件的对不上就会报莫名其妙的错误,比如作者src的hiredis里redisContext,结构如下
typedef struct redisContext {
    int err; /* Error flags, 0 when there is no error */
    char errstr[128]; /* String representation of error when applicable */
    int fd;
    int flags;
    char *obuf; /* Write buffer */
    redisReader *reader; /* Protocol reader */
} redisContext;
但我下载的hiredis里面的源码里面,头文件是这样的
typedef struct redisContext {
    const redisContextFuncs *funcs;   /* Function table */

    int err; /* Error flags, 0 when there is no error */
    char errstr[128]; /* String representation of error when applicable */
    redisFD fd;
    int flags;
    char *obuf; /* Write buffer */
    redisReader *reader; /* Protocol reader */

    enum redisConnectionType connection_type;
    struct timeval *timeout;

    struct {
        char *host;
        char *source_addr;
        int port;
    } tcp;

    struct {
        char *path;
    } unix_sock;

    /* For non-blocking connect */
    struct sockadr *saddr;
    size_t addrlen;

    /* Additional private data for hiredis addons such as SSL */
    void *privdata;
} redisContext;
他俩结构完全对不上,但是因为作者的代码里没有用到后面新加的,所以编译也没报错,就没问题
我翻了半天hiredis的源码,最后才发现,因为两个结构对不上,redisConnectWithTimeout函数返回的时候,
cpp里面的redisContext就乱七八糟了......

**Comment by wanghonglu** [comment]
解决方法就是删掉src下的hiredis.h
然后用自己下载的hiredis里面的头文件
可以在makefile加上 -I(hiredis头文件所在的目录)
就可以了

**Comment by 0xsky** [comment]
hiredis.h 头文件已经去掉了。

**Comment by 0xsky** [comment]
重构了代码，现在应该都可以了。
