### ISSUE TITLE
xRedisClusterClient 不支持带密码的redis集群吗

### ISSUE THREAD

**Issue by jiephe** [0xsky/xredis#56]
`bool xRedisClusterClient::ConnectRedisNode(int32_t idx, const char *host, uint32_t port, uint32_t poolsize)`

`bool xRedisClusterClient::ConnectRedis(const char *host, uint32_t port, uint32_t poolsize)`

**Comment by 0xsky** [comment]
将会支持密码

**Comment by 0xsky** [comment]
已经支持带密码连接redis官方集群了。
