### ISSUE TITLE
建议作者大大把src下的hiredis.h删掉

### ISSUE THREAD

**Issue by wanghonglu** [0xsky/xredis#57]
让用的人自己下载编译hiredis
makefile里面加上-I下载好的hiredis头文件的目录
因为hiredis也更新过几次
如果下载的hiredis跟您src下的头文件版本不一致会出现各种奇怪的错误
我出现了可以编译过但是运行的时候
静态库里生成的redisContext 赋值给cpp里面的时候,由于两者结构不一样导致了错误
望采纳
或者您直接挑一般的hiredis,连源码带头文件全放在自己项目里,这样大家更省事了~~~~

**Comment by 0xsky** [comment]
知道了，这个可以删除掉

**Comment by 0xsky** [comment]
已经删除了，感谢！
