### ISSUE TITLE
Segmentation Fault in RedisPool::GetConnection

### ISSUE THREAD

**Issue by AO-StreetArt** [0xsky/xredis#9]
# Overview
I am writing a helper class to make simple calls to Redis easier, but I am continually receiving a segmentation fault upon requesting or sending any information to the instance.

I think this has to do with the way I'm storing the xRedis and RedisDBIdx instances, and possibly the way I'm storing the RedisAdmin instance within the main application, but I'm unable to see the right way to set these up after several attempts.

Relevant Code is below, and a few notes on debugging steps I have taken myself.

## Debugging Notes
* Redis Server is started successfully, and log output shows successful connection to server on instance startup
* The call fails whether a set or exists command is sent to the server
* GDB Output shows below, and logs show the same happenning on either exists or set calls:

    Program received signal SIGSEGV, Segmentation fault.

    RedisPool::GetConnection (this=0x0, cahcetype=0, dbindex=0, ioType=0) at src/xRedisPool.cpp:124

    124        || (ioType>SLAVE)

### redis_admin.h

    #include "xredis/xRedisClient.h"
    #include <string.h>
    #include <string>

    class xRedisAdmin
    {
    xRedisClient xRedis;
    public:
	    xRedisAdmin(RedisNode conn_list[], int conn_list_size);
	    ~xRedisAdmin();
	    const char * load ( const char * key );
	    bool save ( const char * key, const char * msg );
	    bool exists ( const char * key );
	    bool del ( const char * key );
    };

### redis_admin.cpp

    xRedisAdmin::xRedisAdmin(RedisNode conn_list[], int conn_list_size)
    {
    enum {
    CACHE_TYPE_1,
    CACHE_TYPE_2,
    CACHE_TYPE_MAX,
    };

    xRedis.Init(CACHE_TYPE_MAX);
    bool bret = xRedis.ConnectRedisCache(conn_list, conn_list_size, CACHE_TYPE_1);
    //Log results
    }

    //Exists
    bool xRedisAdmin::exists(const char * key)
    {
    RedisDBIdx d(&xRedis);
    char szKey[256] = {0};
    sprintf(szKey, key);
    return xRedis.exists(d, szKey);
    }

    //Save
    bool xRedisAdmin::save(const char * key, const char * val)
    {
    RedisDBIdx d(&xRedis);
    char szKey[256] = {0};
    sprintf(szKey, key);
    bool ret_val = xRedis.set(d, szKey, val);
    //Log output
    return ret_val;
    }

### Main.cpp

    xRedisAdmin *xRedis;

    void example_callback() {
        bool bRet = xRedis->save("key", "c_str");
    }

    int main()
    {
	  	xRedisAdmin x (RedisList1, conn_list_size);
		xRedis = &x;

        example_callback();
        return 0;
    }

**Comment by AO-StreetArt** [comment]
Tried calling CreateDBIndex after intializing RedisDBIdx, same result

**Comment by 0xsky** [comment]
#include <stdio.h>
#include "xRedisClient.h"

// AP Hash Function
unsigned int APHash(const char *str) {
    unsigned int hash = 0;
    int i;
    for (i=0; *str; i++) {
        if ((i&  1) == 0) {
            hash ^= ((hash << 7) ^ (*str++) ^ (hash >> 3));
        } else {
            hash ^= (~((hash << 11) ^ (*str++) ^ (hash >> 5)));
        }
    }
    return (hash&  0x7FFFFFFF);
}

enum {
 CACHE_TYPE_1,
 CACHE_TYPE_2,
 CACHE_TYPE_MAX,
};

RedisNode RedisList1[1]=
{
    {0,"127.0.0.1", 7000, "", 8, 5, 0}
};


int main(int argc, char **argv) {

    xRedisClient xRedis;
    xRedis.Init(CACHE_TYPE_MAX);
    xRedis.ConnectRedisCache(RedisList1, 1, CACHE_TYPE_1);

    const char *key = "test";
    const char *value = "test value";
    RedisDBIdx dbi(&xRedis);
    dbi.CreateDBIndex(key, APHash, CACHE_TYPE_1);

    bool bRet = xRedis.set(dbi, key, value);
    if(bRet){
        printf("success \r\n");
    } else {
        printf("error [%s] \r\n", dbi.GetErrInfo());
    }

    string strValue;
    bRet = xRedis.get(dbi, key, strValue);
    if (bRet) {
        printf("%s \r\n", strValue.c_str());
    } else {
        printf("error [%s] \r\n", dbi.GetErrInfo());
    }

    return 0;
}



    xRedisClient xRedis;
    xRedis.Init(CACHE_TYPE_MAX);
    xRedis.ConnectRedisCache(RedisList1, 1, CACHE_TYPE_1);

  RedisDBIdx dbi(&xRedis);
  dbi.CreateDBIndex(key, APHash, CACHE_TYPE_1);



2016-06-14 12:11 GMT+08:00 Alex Barry <notifications@github.com>:
